modLoader="javafml" #mandatory
loaderVersion="[34,)"
license="https://www.gnu.org/licenses/gpl-3.0.en.html"
issueTrackerURL="https://github.com/Ocelot5836/Just-Enough-Vehicles/issues" #optional

[[mods]] #mandatory
modId = "${modId}" #mandatory
version = "${modVersion}" #mandatory
displayName = "${modName}" #mandatory
updateJSONURL="https://raw.githubusercontent.com/Ocelot5836/storage/master/mods/just-enough-vehicles/update.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/just-enough-vehicles" #optional
# logoFile="examplemod.png" #optional
# credits="Thanks for this example mod goes to Java" #optional
authors="Ocelot" #optional
description='''
Adds JEI support for MrCrayfish's Vehicle Mod.
'''

[[dependencies.${modId}]]
modId = "forge"
mandatory = true
versionRange = "[34,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "vehicle"
mandatory = true
versionRange = "[0.45.0,)"
ordering = "NONE"
side = "BOTH"
